language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-dev

script:
- cargo build --verbose --all-features
- cargo test --verbose --all-features
