language: rust
rust:
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sndio-tools

script:
- cargo build --verbose --examples --tests --all-features
- cargo test --verbose --all-features
