language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - libsdl2-dev

script:
- cargo build --verbose --examples --tests --all-features
- cargo test --verbose --all-features
