[package]
name = "rs_nes"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"
websocket = { git = "https://github.com/vi/rust-websocket", branch = "optional_openssl" }
iron = "*"
router = "*"
byteorder = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
rand = "*"
seahash = "*"