[package]
name = "rs_nes"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[features]
default = []
debugger = ["iron", "router", "serde", "serde_json", "serde_derive", "seahash", "chan", "byteorder", "websocket", "base64", "png"]


[dependencies]
log = "*"
env_logger = "*"
error-chain = "*"

# Debugger dependencies
websocket = {version = "*", optional = true}
iron = {version = "*", optional = true}
router = {version = "*", optional = true}
byteorder = {version = "*", optional = true}
serde = {version = "^0.9.2", optional = true}
serde_json = {version = "^0.9.1", optional = true}
serde_derive = {version = "^0.9.2", optional = true}
seahash = {version = "*", optional = true}
chan = {version = "^0.1.18", optional = true}
base64 = {version = "^0.4.0", optional = true}
png = {version = "^0.6.2", optional = true}

[dev-dependencies]
asm6502 = {version = "^0.1.2"}
rand = "*"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'