[package]
name = "rs_nes"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[features]
default = []
expensive_tests = []

[dependencies]
log = "*"
env_logger = "*"
websocket = "*"
iron = "*"
router = "*"
byteorder = "*"
serde = "^0.9.2"
serde_json = "^0.9.1"
serde_derive = "^0.9.2"
rand = "*"
seahash = "*"
asm6502 = "0.1.0"
chan = "^0.1.18"