[package]
name = "rs_nes"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[dev-dependencies]
asm6502 = {version = "^0.1.2"}
rand = "*"
time = "*"

[profile.release]
opt-level = 3
lto = true
debug = true
debug-assertions = false
