[package]
name = "rs_nes"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]
build = "build.rs"

[features]
default = []
debugger = ["iron", "router", "serde", "serde_json", "serde_derive", "seahash", "chan", "byteorder", "websocket", "base64", "png", "log", "env_logger"]


[dependencies]
sdl2 = "^0.29.1"

# Debugger dependencies
websocket = {version = "^0.19", optional = true, default-features = false}
iron = {version = "*", optional = true}
router = {version = "*", optional = true}
byteorder = {version = "*", optional = true}
serde = {version = "^0.9.2", optional = true}
serde_json = {version = "^0.9.1", optional = true}
serde_derive = {version = "^0.9.2", optional = true}
seahash = {version = "*", optional = true}
chan = {version = "^0.1.18", optional = true}
base64 = {version = "^0.4.0", optional = true}
png = {version = "^0.6.2", optional = true}
log = {version = "*", optional = true}
env_logger = {version = "*", optional = true}

[dev-dependencies]
asm6502 = {version = "^0.1.2"}
rand = "*"
time = "*"

[[example]]
name = "functional_test_rom"
required-features = ["debugger"]

[[example]]
name = "nes_rom"
required-features = ["debugger"]

[[example]]
name = "generate_ppu_loop"

[[example]]
name = "real_time"

[profile.release]
opt-level = 3
lto = true
debug = true
debug-assertions = false
