[package]
name = "rs-nes-macros"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^0.4"
quote = "^0.6"
syn = { version = "^0.14", default-features = false, features = ["full", "parsing", "proc-macro"] }
