[package]
name = "rs_nes_web"
version = "0.0.1"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[dependencies]
rs_nes = { path = "../../" }
stdweb = "^0.4.6"
env_logger = {version = "*", optional = true}
serde = "1"
serde_derive = "1"